# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_desctription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='desctription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my location default', max_length=120),
        ),
    ]
